### ISSUE TITLE
The gamemode won't work

### ISSUE THREAD

**Issue by PickleJuice12** [d4kir92/GMOD-YourRP#13]
I installed this yourrp-stable.zip and then I unzipped it then I renamed it to "starwarsrp" and then I renamed the .txt to "starwars.txt but it's not working.

**Comment by MaxPlayZ1604** [comment]
I don’t think your supposed to do this…, but I would recommend to use the gamemode via the Steam Workshop [https://steamcommunity.com/sharedfiles/filedetails/?id=1114204152](https://steamcommunity.com/sharedfiles/filedetails/?id=1114204152)

**Comment by PickleJuice12** [comment]
Ok

**Comment by PickleJuice12** [comment]
I'm trying to load into my server(The gamemode is YourRP) but when I load in the screen is black and I can't see, move, or press F4, F8, etc.

**Comment by d4kir92** [comment]
did you tried yourrp only, without any other addons?
