### ISSUE TITLE
I'm trying to load into my server(The gamemode is YourRP) but when I load in the screen is black and I can't see, move, or press F4, F8, etc.

### ISSUE THREAD

**Issue by PickleJuice12** [d4kir92/GMOD-YourRP#14]
I'm trying to load into my server(The gamemode is YourRP) but when I load in the screen is black and I can't see, move, or press F4, F8, etc.

_Originally posted by @PickleJuice12 in https://github.com/d4kir92/yourrp/issues/13#issuecomment-843619397_

**Comment by PickleJuice12** [comment]
[YRP|ERROR] loading => 120+  yrp_received_ready: true yrp_rToSv: true loadedchars: false yrp_hookinitpostentity: true yrp_initpostentity: true YRP_NOINIT: false ENTS: 100 GLOS: 100 dedi: true country: US YRP_COUNT: 0

**Comment by PickleJuice12** [comment]
That's what it says on the console

**Comment by MaxPlayZ1604** [comment]
Does it look like this?

![](https://media.discordapp.net/attachments/344875509383168000/840705982270406666/20210508234254_1.jpg)

**Comment by PickleJuice12** [comment]
No it looks like this: 
![20210518184101_1](https://user-images.githubusercontent.com/84357138/118736691-c936e800-b808-11eb-8898-233be55e9662.jpg)

**Comment by PickleJuice12** [comment]
![20210518184249_1](https://user-images.githubusercontent.com/84357138/118736715-dce24e80-b808-11eb-9b66-82e070242daf.jpg)

**Comment by d4kir92** [comment]
try without any other addons, if it works it must be an addon you have in the collection, please send me the collection then
