### ISSUE TITLE
STDrugs addons "Drug lab" entity is bugged when opening this gamemode on a dedicated server

### ISSUE THREAD

**Issue by FrostbiteTR54** [d4kir92/GMOD-YourRP#15]
STDrugs addon is a drug making addon but it bugs out and cant function properly if you use it on a dedicated server. The entity "Drug bank" clips halfway in the ground and cant be picked up with phsygun also doesnt accept any drug making components

You can replicate this bug by opening a fresh dedicated server with yourrp gamemode and only adding STDrugs,DurgzMod,ULX,YourRP in the collection

![Ekran Alıntısı](https://user-images.githubusercontent.com/71316816/186424828-65fc159a-c164-48d2-bfde-1c6affacde0b.PNG)
.

**Comment by d4kir92** [comment]
link? :D

**Comment by FrostbiteTR54** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1124122444

**Comment by d4kir92** [comment]
i can sell drugs on the "Drug Bank"
https://www.youtube.com/watch?v=ygcIbaf8JjU

**Comment by FrostbiteTR54** [comment]
> i can sell drugs on the "Drug Bank" https://www.youtube.com/watch?v=ygcIbaf8JjU

The "Drug Bank" works fine for me too i was talking about Drug Lab

**Comment by d4kir92** [comment]
ok how does the drug lab work?

**Comment by d4kir92** [comment]
the drug lab has no collision or?

**Comment by d4kir92** [comment]
it works now for me when i added CS:S Content (Models + Materials) on SERVER + Client
when the server doesn't know the model it doesn't have collision

https://i.imgur.com/gTGJ5mD.png

**Comment by FrostbiteTR54** [comment]
thanks so much this might actually work i didnt know i hadd to add css content to the server.

**Comment by d4kir92** [comment]
can be done manually by moving css content on server 

or easy way => via workshop, there might some workshop addons that includes css content :P

**Comment by FrostbiteTR54** [comment]
i added the css content addon from your collection and it finally worked thanks so much man you made my day better
