### ISSUE TITLE
"Armor Follow" bug on EFT Equipment Props + JMOD Armor Addon 

### ISSUE THREAD

**Issue by FrostbiteTR54** [d4kir92/GMOD-YourRP#16]
https://www.youtube.com/watch?v=5F1jWVIpktI

You can look at what i mean by "Armor Follow" by watching this short video but basically when you equip the armor it follows the playermodel instead of sticking to it
This only happens in YourRP gamemode on a dedicated server, i have tried sandbox dedicated server and the addon works fine

**Comment by d4kir92** [comment]
link? :D

**Comment by FrostbiteTR54** [comment]
> link? :D

https://steamcommunity.com/sharedfiles/filedetails/?id=2804625575

**Comment by d4kir92** [comment]
strange it works for me in yourrp
https://www.youtube.com/watch?v=EJA6yb6rAVY

it may caused by another addon that needs an RP Gamemode, not sure :D

**Comment by FrostbiteTR54** [comment]
ok thanks i will make my friend open a dedicated server and see if he has it as well  thanks for your help 
Btw did you record the video while you were on a dedicated server? because it only happens on a dedicated server

**Comment by d4kir92** [comment]
i always use a dedicated server :D
but a lot of addons can break those things

i used this collection:
https://steamcommunity.com/sharedfiles/filedetails/?id=1677567005

**Comment by d4kir92** [comment]
it may caused by animation addons, let me know which addon is breaking it :D

**Comment by FrostbiteTR54** [comment]
im not sure partly because i cant belive it myself but this map might be breaking it
https://steamcommunity.com/sharedfiles/filedetails/?id=1601428630&searchtext=rp_truenorth
i opened a dedicated server with the collection below on gm_construct in yourrp gamemode and it worked as intended then reopened the server on rp_truenorth and the "Armor Follow" happened again
The collection i tried this with
https://steamcommunity.com/sharedfiles/filedetails/?id=2852766041

**Comment by FrostbiteTR54** [comment]
hey dakir can you try opening the dedicated server on a different map to replicate the issue because on gm construct and flatgrass it works fine for me too
try this map for example https://steamcommunity.com/sharedfiles/filedetails/?id=1601428630&searchtext=rp_truenorth
if it still works for you, feel free to close this issue

**Comment by d4kir92** [comment]
works also for me

90% sure its a "lib" oder "animation" addon causing this on your video

**Comment by FrostbiteTR54** [comment]
This problem while still not fixed, became a non problem(for me) when i realized that other players see you normally. Only you see the "Armor Follow" on yourself and yourself only.

**Comment by d4kir92** [comment]
ah ok, but only when you have low fps or?

**Comment by FrostbiteTR54** [comment]
no it has nothing to do with fps since i tested it but if it happens to anyone pls use this thirdperson mod below to see your armor correctly. This is the only workaround i have found so far turn off YourRP Thirdperson btw

TPS MOD:https://steamcommunity.com/sharedfiles/filedetails/?id=108168164&searchtext=customizable+thirdperson

**Comment by d4kir92** [comment]
what, it works for me with yourrp thirdperson :D
